USE studentportal;

insert into `inventoryitem`(`ItemID`,`ItemCategory`,`ItemName`,`ItemConfiguration`,`ItemCondition`,`ItemEmployee`,`ItemDate`,`ItemStatus`,`ItemImage`,`isActive`) values (1,1,'Samsung Tab','Samsung Tab S2,Android 7.0 Noughat,32 GB RAM','Good, Tempered Glass Already Cracked.',0,'2018-05-03 12:00:51',0,'',0);
insert into `inventoryitem`(`ItemID`,`ItemCategory`,`ItemName`,`ItemConfiguration`,`ItemCondition`,`ItemEmployee`,`ItemDate`,`ItemStatus`,`ItemImage`,`isActive`) values (2,1,'Macbook Pro Laptop : End-2013','Ram:16GB, HDD:512GB, along with Adaptor ','Good',0,'2018-03-09 12:03:18',0,'',0);
insert into `inventoryitem`(`ItemID`,`ItemCategory`,`ItemName`,`ItemConfiguration`,`ItemCondition`,`ItemEmployee`,`ItemDate`,`ItemStatus`,`ItemImage`,`isActive`) values (3,1,'Wireless Keyboard','Logitech Wireless Keyboard, white& black colored','Good',0,'2018-03-09 12:01:06',0,'',0);
insert into `inventoryitem`(`ItemID`,`ItemCategory`,`ItemName`,`ItemConfiguration`,`ItemCondition`,`ItemEmployee`,`ItemDate`,`ItemStatus`,`ItemImage`,`isActive`) values (4,1,'Wireless Mouse','Logitech black & white Colored wireless mouse','Good',0,'2018-03-09 12:02:42',0,'',0);
insert into `inventoryitem`(`ItemID`,`ItemCategory`,`ItemName`,`ItemConfiguration`,`ItemCondition`,`ItemEmployee`,`ItemDate`,`ItemStatus`,`ItemImage`,`isActive`) values (5,1,'Apple Ipad WIFI Only','32 GB Ram, 9.7 Inch, With Connecting Cable','Good, No damage',0,'2018-05-03 10:11:27',0,'',0);
insert into `inventoryitem`(`ItemID`,`ItemCategory`,`ItemName`,`ItemConfiguration`,`ItemCondition`,`ItemEmployee`,`ItemDate`,`ItemStatus`,`ItemImage`,`isActive`) values (6,1,'Nexus 5','Android Mobile, 16Gb Ram, No SD card','Good Condition with back cover',0,'2018-06-05 12:51:55',0,'',0);
insert into `inventoryitem`(`ItemID`,`ItemCategory`,`ItemName`,`ItemConfiguration`,`ItemCondition`,`ItemEmployee`,`ItemDate`,`ItemStatus`,`ItemImage`,`isActive`) values (7,1,'MacBook Pro : Mid-2014','Retina, 15 inch, MID 2014, 2.5 GHz intel Core i7 ,16 GB DDR3 ,Serial Number: C02N80N4G33QN, with Charger, Version
: Mid-2014 ','Good Condition',0,'2018-06-06 04:12:49',0,'',0);
insert into `inventoryitem`(`ItemID`,`ItemCategory`,`ItemName`,`ItemConfiguration`,`ItemCondition`,`ItemEmployee`,`ItemDate`,`ItemStatus`,`ItemImage`,`isActive`) values (8,1,'Lenovo T440P ','laptop with Charger ','Good Condition',0,'2018-06-06 04:13:50',0,'',0);
insert into `inventoryitem`(`ItemID`,`ItemCategory`,`ItemName`,`ItemConfiguration`,`ItemCondition`,`ItemEmployee`,`ItemDate`,`ItemStatus`,`ItemImage`,`isActive`) values (9,1,'Iphone 6s Plus','Gray Color, 64 GB, mobile only, No Charger, No Headphones.','Good Condition, Temper class has crack',0,'2018-06-06 04:14:44',0,'',0);
insert into `inventoryitem`(`ItemID`,`ItemCategory`,`ItemName`,`ItemConfiguration`,`ItemCondition`,`ItemEmployee`,`ItemDate`,`ItemStatus`,`ItemImage`,`isActive`) values (10,1,'VOYO OBD2','device and Connecting Cable','Used, good condition',0,'2018-06-06 04:18:46',0,'',0);
insert into `inventoryitem`(`ItemID`,`ItemCategory`,`ItemName`,`ItemConfiguration`,`ItemCondition`,`ItemEmployee`,`ItemDate`,`ItemStatus`,`ItemImage`,`isActive`) values (11,1,'OBD2 emilator','device and Charger','Used , Good Condition',0,'2018-06-06 04:16:14',0,'',0);
insert into `inventoryitem`(`ItemID`,`ItemCategory`,`ItemName`,`ItemConfiguration`,`ItemCondition`,`ItemEmployee`,`ItemDate`,`ItemStatus`,`ItemImage`,`isActive`) values (12,1,'Test','Laptop  treer','Newggg',0,'2018-07-12 13:07:53',0,'',0);
insert into `inventoryitem`(`ItemID`,`ItemCategory`,`ItemName`,`ItemConfiguration`,`ItemCondition`,`ItemEmployee`,`ItemDate`,`ItemStatus`,`ItemImage`,`isActive`) values (13,1,'MacBook Pro (Retina, 15-inch, Mid 2014)','Ram: 16 GB 1600 MHz DDR3, I7 @.5 GHz, Graphics: Intel Iris Pro 1536 MB, Serial Number: C02NM0X8G3QN, with Adaptor','Good',0,'2018-10-05 10:01:43',0,'5bb736872249c.jpeg',1);
