USE studentportal;

insert into `officialleave`(`OfficialID`,`OfficialLeave`,`OfficialLeaveFrom`,`OfficialLeaveDay`,`OfficialStatus`,`OfficialCreatedBy`,`OfficialDateCreated`,`OfficialModifiedBy`,`OfficialDateModified`) values (1,'Christmas','2017-12-25','Monday',1,1,'2017-12-05 17:37:50',0,null);
insert into `officialleave`(`OfficialID`,`OfficialLeave`,`OfficialLeaveFrom`,`OfficialLeaveDay`,`OfficialStatus`,`OfficialCreatedBy`,`OfficialDateCreated`,`OfficialModifiedBy`,`OfficialDateModified`) values (2,'New Year','2018-01-01','Monday',1,1,'2017-12-05 17:38:38',0,null);
insert into `officialleave`(`OfficialID`,`OfficialLeave`,`OfficialLeaveFrom`,`OfficialLeaveDay`,`OfficialStatus`,`OfficialCreatedBy`,`OfficialDateCreated`,`OfficialModifiedBy`,`OfficialDateModified`) values (3,'Pongal & Tamil New Years Day ','2018-01-14','Sunday',1,1,'2018-01-03 00:00:00',0,null);
insert into `officialleave`(`OfficialID`,`OfficialLeave`,`OfficialLeaveFrom`,`OfficialLeaveDay`,`OfficialStatus`,`OfficialCreatedBy`,`OfficialDateCreated`,`OfficialModifiedBy`,`OfficialDateModified`) values (4,'Thiruvalluvar Day (State Government Holiday)','2018-01-15','Monday',1,1,'2018-01-03 00:00:00',0,null);
insert into `officialleave`(`OfficialID`,`OfficialLeave`,`OfficialLeaveFrom`,`OfficialLeaveDay`,`OfficialStatus`,`OfficialCreatedBy`,`OfficialDateCreated`,`OfficialModifiedBy`,`OfficialDateModified`) values (5,'Republic Day','2018-01-26','Friday',1,1,'2018-01-03 00:00:00',0,null);
insert into `officialleave`(`OfficialID`,`OfficialLeave`,`OfficialLeaveFrom`,`OfficialLeaveDay`,`OfficialStatus`,`OfficialCreatedBy`,`OfficialDateCreated`,`OfficialModifiedBy`,`OfficialDateModified`) values (6,'Good Friday','2018-03-30','Friday',1,1,'2018-01-03 00:00:00',0,null);
insert into `officialleave`(`OfficialID`,`OfficialLeave`,`OfficialLeaveFrom`,`OfficialLeaveDay`,`OfficialStatus`,`OfficialCreatedBy`,`OfficialDateCreated`,`OfficialModifiedBy`,`OfficialDateModified`) values (7,'May Day ? labour Day','2018-05-01','Tuesday',1,1,'2018-01-03 00:00:00',0,null);
insert into `officialleave`(`OfficialID`,`OfficialLeave`,`OfficialLeaveFrom`,`OfficialLeaveDay`,`OfficialStatus`,`OfficialCreatedBy`,`OfficialDateCreated`,`OfficialModifiedBy`,`OfficialDateModified`) values (8,'Independence Day','2018-08-15','Wednesday',1,1,'2018-01-03 00:00:00',0,null);
insert into `officialleave`(`OfficialID`,`OfficialLeave`,`OfficialLeaveFrom`,`OfficialLeaveDay`,`OfficialStatus`,`OfficialCreatedBy`,`OfficialDateCreated`,`OfficialModifiedBy`,`OfficialDateModified`) values (9,'Vinayakar Chathurthi','2018-09-13','Thursday',1,1,'2018-01-03 00:00:00',0,null);
insert into `officialleave`(`OfficialID`,`OfficialLeave`,`OfficialLeaveFrom`,`OfficialLeaveDay`,`OfficialStatus`,`OfficialCreatedBy`,`OfficialDateCreated`,`OfficialModifiedBy`,`OfficialDateModified`) values (10,'Gandhi Jayanthi','2018-10-02','Tuesday',1,1,'2018-01-03 00:00:00',0,null);
insert into `officialleave`(`OfficialID`,`OfficialLeave`,`OfficialLeaveFrom`,`OfficialLeaveDay`,`OfficialStatus`,`OfficialCreatedBy`,`OfficialDateCreated`,`OfficialModifiedBy`,`OfficialDateModified`) values (11,'Ayudha Pooja','2018-10-18','Thursday',1,1,'2018-01-03 00:00:00',0,null);
insert into `officialleave`(`OfficialID`,`OfficialLeave`,`OfficialLeaveFrom`,`OfficialLeaveDay`,`OfficialStatus`,`OfficialCreatedBy`,`OfficialDateCreated`,`OfficialModifiedBy`,`OfficialDateModified`) values (12,'Deepavali','2018-11-06','Tuesday',1,1,'2018-01-03 00:00:00',0,null);
insert into `officialleave`(`OfficialID`,`OfficialLeave`,`OfficialLeaveFrom`,`OfficialLeaveDay`,`OfficialStatus`,`OfficialCreatedBy`,`OfficialDateCreated`,`OfficialModifiedBy`,`OfficialDateModified`) values (13,'Christmas','2018-12-25','Tuesday',1,1,'2018-01-03 00:00:00',0,null);
